project:
  type: website
  output-dir: _site
execute:
  freeze: auto
website:
  title: "Updating Priors"
  site-url: https://stcolema.github.io/
  description: "Bayesian model-based clustering"
  image: onyx_ball.jpg
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/stcolema
format:
  html:
    theme:
      light: lumen
      dark: darkly
    css: styles.css
